
HOLDING_CELL1_MS = 0
HOLDING_CELL1_LS = 1
HOLDING_CELL2_MS = 2
HOLDING_CELL2_LS = 3
HOLDING_CELL3_MS = 4
HOLDING_CELL3_LS = 5
HOLDING_CELL4_MS = 6
HOLDING_CELL4_LS = 7
HOLDING_PESO_TOT_MS = 8
HOLDING_PESO_TOT_LS = 9
HOLDING_PESO_CALIB_MS = 10
HOLDING_PESO_CALIB_LS = 11
CONNECTION_DUMMY = 12
COUNT = 13
DIAGNOSTIC = 14

# Costanti per i coil
COIL_PESO_COMMAND = 0
COIL_TARE_COMMAND = 1
COIL_CALIB_COMMAND = 2
COIL_LAST_COMMAND_SUCCESS = 3
COIL_PRESENCE_STATUS = 4
COIL_CELL_STATUS = 5
COIL_ADCS_STATUS = 6
COIL_CONFIG = 7
